# Prettier configuration https://prettier.io/docs/en/configuration.html

"arrowParens": "always"
"bracketSpacing": true
"endOfLine": "lf"
"semi": false
"singleQuote": false
"tabWidth": 2
"trailingComma": "es5"
"printWidth": 120
"useTabs": false
